### ISSUE TITLE
guess_by_extension throws exception on files without extension

### ISSUE THREAD

**Issue by driesmoors** [matthewdeanmartin/whats_that_code#1]
When feeding it with files without an extension, an exception is thrown:

```
>>> e.guess_language_all_methods(code, 'myfile')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\whats_that_code\election.py", line 35, in guess_language_all_methods
    vote_by_extension = guess_by_extension(file_name=file_name)
  File "C:\Users\ME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\whats_that_code\extension_based.py", line 19, in guess_by_extension
    extensions.append("." + file_name.split(".")[1])
IndexError: list index out of range
```

Better seems to use `os.path.splitext(file)[1]` to retrieve the extension.

**Comment by matthewdeanmartin** [comment]
I pushed my untested fix to https://github.com/matthewdeanmartin/whats_that_code/blob/main/whats_that_code/extension_based.py 

I'll test it & push out a release to pypi this weekend.

Thanks for trying out my library!

**Comment by driesmoors** [comment]
Works fine now. Thanks for the quick fix.
