### ISSUE TITLE
exception TypeError in shebang_based.py

### ISSUE THREAD

**Issue by driesmoors** [matthewdeanmartin/whats_that_code#2]
Using a file with just two lines:

```
#!/usr/bin/make -f
# 

```
Stored as `_usr_bin_make -f.txt`:

```
>>> import whats_that_code.election
>>> with open(r'_usr_bin_make -f.txt', 'r', encoding='utf-8-sig', errors='ignore') as file_handle:
...     text = file_handle.read()
...
>>> guessed_language = whats_that_code.election.guess_language_all_methods(text, file_name=file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\whats_that_code\election.py", line 34, in guess_language_all_methods
    vote_by_shebang = language_by_shebang(code)
  File "C:\Users\ME\AppData\Local\Programs\Python\Python37-32\lib\site-packages\whats_that_code\shebang_based.py", line 56, in language_by_shebang
    raise TypeError()
TypeError
```

(running 0.1.11)

**Comment by driesmoors** [comment]
Hi,

Can you have a look at this patch? It may solve this issue.

Best,
Dries.
[patch_#2.zip](https://github.com/matthewdeanmartin/whats_that_code/files/6097132/patch_.2.zip)

**Comment by matthewdeanmartin** [comment]
Took 5 years, but the fix is out: https://github.com/matthewdeanmartin/whats_that_code/releases/tag/v0.3.1

Also, MRs are far preferable than zips.
